// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB20bdfh04Bl0goNGaUD1wsxSd2gDdyRUk',
    appId: '1:172865199625:android:569078adfedaa546d2e2d8',
    messagingSenderId: '172865199625',
    projectId: 'smartkoi-2019',
    databaseURL: 'https://smartkoi-2019-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartkoi-2019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjFbZt_dDFNS5HsNMZaTE1zVyQQXxsjuI',
    appId: '1:172865199625:ios:e212fda016ed5e92d2e2d8',
    messagingSenderId: '172865199625',
    projectId: 'smartkoi-2019',
    databaseURL: 'https://smartkoi-2019-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartkoi-2019.firebasestorage.app',
    iosBundleId: 'com.example.smartkoi',
  );
}